version: '3'

services:
  app:
    container_name: app_laravel12
    build: .
    ports:
        -   "8000:8000"
#    user: "www:www" # <-- Đảm bảo PHP chạy bằng user phù hợp
    user: root
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./php.ini:/usr/local/etc/php/php.ini

  redis:
      image: redis:latest
      container_name: redis_for_laravel_octance
      ports:
          -   "63792:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "5672:5672"       # RabbitMQ broker port
        - "15672:15672"     # Management UI port
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false # tat security cho de test
        - ES_JAVA_OPTS=-Xms1g -Xmx1g # gioi han RAM cho JVM
    ports:
        - "9200:9200" # API Elasticsearch
    volumes:
        -   es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
        -   "5601:5601" # UI Kibana for elasticsearch
    depends_on:
        -   elasticsearch

volumes:
    es_data:
        driver: local
