version: '3'

services:
  app:
    container_name: app_laravel12
    build: .
    ports:
        -   "8000:8000"
#    user: "www:www" # <-- Đảm bảo PHP chạy bằng user phù hợp
    user: root
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./php.ini:/usr/local/etc/php/php.ini

  redis:
      image: redis:latest
      container_name: redis_for_laravel_octance
      ports:
          -   "63792:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "5672:5672"       # RabbitMQ broker port
        - "15672:15672"     # Management UI port
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
